// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Expression")>]
[<assembly: AssemblyProductAttribute("FSharp.Expression")>]
[<assembly: AssemblyDescriptionAttribute("F# Implementation for expression parsing")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Expression"
    let [<Literal>] AssemblyProduct = "FSharp.Expression"
    let [<Literal>] AssemblyDescription = "F# Implementation for expression parsing"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
